export const sampleArticles = [
  {
    id: "one",
    title: "sample",
    description: "sample",
    content: "sample",
    tags: "Node.js, JavaScript",
    authorName: "SMLukwiya",
    createdAt: Date.now().toLocaleString(),
    updatedAt: Date.now().toLocaleString(),
  },
  {
    id: "two",
    title: "sample",
    description: "sample",
    content: "sample",
    tags: "React",
    authorName: "SMLukwiya",
    createdAt: Date.now().toLocaleString(),
    updatedAt: Date.now().toLocaleString(),
  },
  {
    id: "three",
    title: "sample",
    description: "sample",
    content: "sample",
    tags: "Next.js, Prisma",
    authorName: "SMLukwiya",
    createdAt: Date.now().toLocaleString(),
    updatedAt: Date.now().toLocaleString(),
  },
  {
    id: "four",
    title: "sample",
    description: "sample",
    content: "sample",
    tags: "React",
    authorName: "SMLukwiya",
    createdAt: Date.now().toLocaleString(),
    updatedAt: Date.now().toLocaleString(),
  },
  {
    id: "five",
    title: "sample",
    description: "sample",
    content: "sample",
    tags: "React Native, Typescript",
    authorName: "SMLukwiya",
    createdAt: Date.now().toLocaleString(),
    updatedAt: Date.now().toLocaleString(),
  },
  {
    id: "six",
    title: "sample",
    description: "sample",
    content: "sample",
    tags: "",
    authorName: "SMLukwiya",
    createdAt: Date.now().toLocaleString(),
    updatedAt: Date.now().toLocaleString(),
  },
  {
    id: "seven",
    title: "sample",
    description: "sample",
    content: "sample",
    tags: "",
    authorName: "SMLukwiya",
    createdAt: Date.now().toLocaleString(),
    updatedAt: Date.now().toLocaleString(),
  },
];
